version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Selenium tests
          command: |
            npm test
