version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18.15.8-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run Selenium tests
          command: |
            npm test
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
          destination: mochawesome_reports/

